apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todobot.fullname" . }}-secret
  labels:
    {{- include "todobot.labels" . | nindent 4 }}
type: Opaque
data:
  TELEGRAM_TOKEN: {{ .Values.env.TELEGRAM_TOKEN | b64enc | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | b64enc | quote }}
